/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SubcategoryService } from "../subcategory.service";
import { SubcategoryCreateInput } from "./SubcategoryCreateInput";
import { Subcategory } from "./Subcategory";
import { SubcategoryFindManyArgs } from "./SubcategoryFindManyArgs";
import { SubcategoryWhereUniqueInput } from "./SubcategoryWhereUniqueInput";
import { SubcategoryUpdateInput } from "./SubcategoryUpdateInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

export class SubcategoryControllerBase {
  constructor(protected readonly service: SubcategoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Subcategory })
  async createSubcategory(
    @common.Body() data: SubcategoryCreateInput
  ): Promise<Subcategory> {
    return await this.service.createSubcategory({
      data: {
        ...data,

        category: data.category
          ? {
              connect: data.category,
            }
          : undefined,
      },
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Subcategory] })
  @ApiNestedQuery(SubcategoryFindManyArgs)
  async subcategories(@common.Req() request: Request): Promise<Subcategory[]> {
    const args = plainToClass(SubcategoryFindManyArgs, request.query);
    return this.service.subcategories({
      ...args,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Subcategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async subcategory(
    @common.Param() params: SubcategoryWhereUniqueInput
  ): Promise<Subcategory | null> {
    const result = await this.service.subcategory({
      where: params,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Subcategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSubcategory(
    @common.Param() params: SubcategoryWhereUniqueInput,
    @common.Body() data: SubcategoryUpdateInput
  ): Promise<Subcategory | null> {
    try {
      return await this.service.updateSubcategory({
        where: params,
        data: {
          ...data,

          category: data.category
            ? {
                connect: data.category,
              }
            : undefined,
        },
        select: {
          category: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Subcategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSubcategory(
    @common.Param() params: SubcategoryWhereUniqueInput
  ): Promise<Subcategory | null> {
    try {
      return await this.service.deleteSubcategory({
        where: params,
        select: {
          category: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/products")
  @ApiNestedQuery(ProductFindManyArgs)
  async findProducts(
    @common.Req() request: Request,
    @common.Param() params: SubcategoryWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProducts(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        price: true,

        subcategory: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/products")
  async connectProducts(
    @common.Param() params: SubcategoryWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        connect: body,
      },
    };
    await this.service.updateSubcategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/products")
  async updateProducts(
    @common.Param() params: SubcategoryWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        set: body,
      },
    };
    await this.service.updateSubcategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/products")
  async disconnectProducts(
    @common.Param() params: SubcategoryWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        disconnect: body,
      },
    };
    await this.service.updateSubcategory({
      where: params,
      data,
      select: { id: true },
    });
  }
}
